name: golang-unit-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:

    name: test

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go-version: [ '1.24' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - run: go mod download
      - run: go test -v -race ./...